The plugin provides a set of tags you can use to render the fields in a form.

In the simplest case you can use _f:all_ to render a field for every property of a bean (the domain object or command the form will bind to):

[source,groovy]
----
<g:form…>
    <f:all bean="person"/>
</g:form>
----

To render individual fields you use the _f:field_ tag:

[source,groovy]
----
<g:form…>
    <f:field bean="person" property="name"/>
    <f:field bean="person" property="address"/>
    <f:field bean="person" property="dateOfBirth"/>
</g:form>
----

The _f:field_ tag will automatically handle embedded domain properties recursively:

[source,groovy]
----
<f:field bean="person" property="address"/>
----

If there is no bean object backing a form but you still want to render the surrounding field markup you can give _f:field_ a body:

[source,groovy]
----
<f:field property="password">
    <g:password name="password"/>
</f:field>
----

It should be an unusual case but to render just the widget without its surrounding container you can use the _f:widget_ tag:

[source,groovy]
----
<f:widget bean="person" property="name"/>
----

To make it more convenient when rendering lots of properties of the same _bean_ you can use the _f:with_ tag to avoid having to specify _bean_ on any tags nested inside:

[source,groovy]
----
<g:form…>
    <f:with bean="person">
        <f:field property="name"/>
        <f:field property="address"/>
        <f:field property="dateOfBirth"/>
    </f:with>
</g:form>
----

If you need to render a property for display purposes you can use _f:display_. It will internally use _g:fieldValue_, _g:formatBoolean_ or _g:formatDate_ to format the value.

[source,groovy]
----
<f:display bean="person" property="name"/>
----

If you need to render the value in a different way you can give _f:display_ a body instead.

[source,groovy]
----
<f:display bean="person" property="dateOfBirth">
    <g:formatDate format="dd MMM yyyy" date="${value}"/>
</f:display>
----

By default _f:display_ simply renders the property value but if you supply a _\_display.gsp_ template you can render the value in some structured markup, e.g. a table cell or list item. See the <<customizingFieldRendering,Customizing Field Rendering>> section for how to override templates. For example to render values in a definition list you could use a template like this:

[source,groovy]
----
<dt>${label}</dt>
<dd>${value}</dd>
----


=== Extra attributes (Since version 2.1.4)


You can pass any number of extra attributes to the _f:with_ and _f:all_ tags that will be propagated to the inner fields and displays.
See their individual tags sections for more information.


=== Breaking changes



=== Templates

The names of the templates were changed for more adequate ones:
* _field to _wrapper
* _input to _widget
* _display to _displayWrapper
* _displayWidget was added

To use the old names (for backwards compatibility), configure the following in `Config.groovy`

[source,groovy]
----
grails.plugin.fields.wrapper = "field"
grails.plugin.fields.displayWrapper = "display"
grails.plugin.fields.widget = "input"
----


=== Widget attributes

To pass additional attributes to widgets, prefix them with 'widget-'.

Example:
[source,groovy]
----
<f:field property="birthDate" widget-format="dd/MM/yyyy"/>
----

To use the old prefix (for backwards compatibility), configure the following in `Config.groovy`:
[source,groovy]
----
grails.plugin.fields.widgetPrefix = "input-"
----


=== Changes in tags

* The _input_ tag was deprecated because the name was confusing. Use the new _widget_ tag instead.
* The _displayWidget_ tag was added. It outputs the widget for display purposes, without the wrapper (similar to the _widget_ tag).